/* eslint-disable */
// WARNING: DO NOT EDIT. This file is automatically generated by AWS Amplify. It will be overwritten.

const awsmobile = {
    "aws_project_region": "us-east-1",
    "aws_appsync_graphqlEndpoint": "https://42dcnezudnfblip6673ztxctym.appsync-api.us-east-1.amazonaws.com/graphql",
    "aws_appsync_region": "us-east-1",
    "aws_appsync_authenticationType": "API_KEY",
    "aws_appsync_apiKey": "da2-5knalj7jwngjrf3xjgl5bqhyom",
    "aws_cognito_identity_pool_id": "us-east-1:cfee3b7d-ae61-404a-bd39-0057fc0ea1ef",
    "aws_cognito_region": "us-east-1",
    "aws_user_pools_id": "us-east-1_Yc6NoMjkT",
    "aws_user_pools_web_client_id": "3m1jr3jieidn8v6mm524gbf724",
    "oauth": {},
    "aws_cognito_username_attributes": [],
    "aws_cognito_social_providers": [],
    "aws_cognito_signup_attributes": [
        "EMAIL"
    ],
    "aws_cognito_mfa_configuration": "OFF",
    "aws_cognito_mfa_types": [
        "SMS"
    ],
    "aws_cognito_password_protection_settings": {
        "passwordPolicyMinLength": 8,
        "passwordPolicyCharacters": []
    },
    "aws_cognito_verification_mechanisms": [
        "EMAIL"
    ]
};


export default awsmobile;
