/* eslint-disable */
// WARNING: DO NOT EDIT. This file is automatically generated by AWS Amplify. It will be overwritten.

const awsmobile = {
    "aws_project_region": "us-east-1",
    "aws_appsync_graphqlEndpoint": "https://peemz27hzbd6bbvzzqlsynyh6a.appsync-api.us-east-1.amazonaws.com/graphql",
    "aws_appsync_region": "us-east-1",
    "aws_appsync_authenticationType": "API_KEY",
    "aws_appsync_apiKey": "da2-wo3mhp5j7bbj3nbltg5cggt47u",
    "aws_cognito_identity_pool_id": "us-east-1:454fd815-cf4b-4f25-bb85-bca353cf81f7",
    "aws_cognito_region": "us-east-1",
    "aws_user_pools_id": "us-east-1_aFxMZSNQY",
    "aws_user_pools_web_client_id": "3ti6a3otbetmuur8bvgnsbkndr",
    "oauth": {},
    "aws_cognito_username_attributes": [],
    "aws_cognito_social_providers": [],
    "aws_cognito_signup_attributes": [
        "EMAIL"
    ],
    "aws_cognito_mfa_configuration": "OFF",
    "aws_cognito_mfa_types": [
        "SMS"
    ],
    "aws_cognito_password_protection_settings": {
        "passwordPolicyMinLength": 8,
        "passwordPolicyCharacters": []
    },
    "aws_cognito_verification_mechanisms": [
        "EMAIL"
    ]
};


export default awsmobile;
